# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PositionModeResponse

    PositionModeResponse(;
        dualSidePosition=nothing,
    )

    - dualSidePosition::Bool : true-hedge mode, false-one-way mode
"""
Base.@kwdef mutable struct PositionModeResponse <: OpenAPI.APIModel
    dualSidePosition::Union{Nothing, Bool} = nothing

    function PositionModeResponse(dualSidePosition, )
        OpenAPI.validate_property(PositionModeResponse, Symbol("dualSidePosition"), dualSidePosition)
        return new(dualSidePosition, )
    end
end # type PositionModeResponse

const _property_types_PositionModeResponse = Dict{Symbol,String}(Symbol("dualSidePosition")=>"Bool", )
OpenAPI.property_type(::Type{ PositionModeResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PositionModeResponse[name]))}

function check_required(o::PositionModeResponse)
    true
end

function OpenAPI.validate_property(::Type{ PositionModeResponse }, name::Symbol, val)
end
