name = "BinanceFuturesAPI"
uuid = "e7367a70-cccc-493b-bb7b-60e2dbc84416"
authors = ["Thomas Wenrich <twenrich@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
OpenAPI = "d5e62ea6-ddf3-4d43-8e4c-ad5e6c8bfd7d"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
Dates = "1.11.0"
OpenAPI = "0.1.26"
TimeZones = "1.19.0"
