# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ExchangeInfoResponse_assets_inner

    ExchangeInfoResponseAssetsInner(;
        asset=nothing,
        marginAvailable=nothing,
        autoAssetExchange=nothing,
    )

    - asset::String
    - marginAvailable::Bool
    - autoAssetExchange::Float64
"""
Base.@kwdef mutable struct ExchangeInfoResponseAssetsInner <: OpenAPI.APIModel
    asset::Union{Nothing, String} = nothing
    marginAvailable::Union{Nothing, Bool} = nothing
    autoAssetExchange::Union{Nothing, Float64} = nothing

    function ExchangeInfoResponseAssetsInner(asset, marginAvailable, autoAssetExchange, )
        OpenAPI.validate_property(ExchangeInfoResponseAssetsInner, Symbol("asset"), asset)
        OpenAPI.validate_property(ExchangeInfoResponseAssetsInner, Symbol("marginAvailable"), marginAvailable)
        OpenAPI.validate_property(ExchangeInfoResponseAssetsInner, Symbol("autoAssetExchange"), autoAssetExchange)
        return new(asset, marginAvailable, autoAssetExchange, )
    end
end # type ExchangeInfoResponseAssetsInner

const _property_types_ExchangeInfoResponseAssetsInner = Dict{Symbol,String}(Symbol("asset")=>"String", Symbol("marginAvailable")=>"Bool", Symbol("autoAssetExchange")=>"Float64", )
OpenAPI.property_type(::Type{ ExchangeInfoResponseAssetsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ExchangeInfoResponseAssetsInner[name]))}

function check_required(o::ExchangeInfoResponseAssetsInner)
    true
end

function OpenAPI.validate_property(::Type{ ExchangeInfoResponseAssetsInner }, name::Symbol, val)
end
