# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""MultiAssetsMarginResponse

    MultiAssetsMarginResponse(;
        multiAssetsMargin=nothing,
    )

    - multiAssetsMargin::Bool : Whether multi-assets mode is enabled
"""
Base.@kwdef mutable struct MultiAssetsMarginResponse <: OpenAPI.APIModel
    multiAssetsMargin::Union{Nothing, Bool} = nothing

    function MultiAssetsMarginResponse(multiAssetsMargin, )
        OpenAPI.validate_property(MultiAssetsMarginResponse, Symbol("multiAssetsMargin"), multiAssetsMargin)
        return new(multiAssetsMargin, )
    end
end # type MultiAssetsMarginResponse

const _property_types_MultiAssetsMarginResponse = Dict{Symbol,String}(Symbol("multiAssetsMargin")=>"Bool", )
OpenAPI.property_type(::Type{ MultiAssetsMarginResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MultiAssetsMarginResponse[name]))}

function check_required(o::MultiAssetsMarginResponse)
    true
end

function OpenAPI.validate_property(::Type{ MultiAssetsMarginResponse }, name::Symbol, val)

end
