# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PositionModeResponse

    PositionModeResponse(;
        code=nothing,
        msg=nothing,
    )

    - code::Int64 : Response code
    - msg::String : Response message
"""
Base.@kwdef mutable struct PositionModeResponse <: OpenAPI.APIModel
    code::Union{Nothing, Int64} = nothing
    msg::Union{Nothing, String} = nothing

    function PositionModeResponse(code, msg, )
        OpenAPI.validate_property(PositionModeResponse, Symbol("code"), code)
        OpenAPI.validate_property(PositionModeResponse, Symbol("msg"), msg)
        return new(code, msg, )
    end
end # type PositionModeResponse

const _property_types_PositionModeResponse = Dict{Symbol,String}(Symbol("code")=>"Int64", Symbol("msg")=>"String", )
OpenAPI.property_type(::Type{ PositionModeResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PositionModeResponse[name]))}

function check_required(o::PositionModeResponse)
    true
end

function OpenAPI.validate_property(::Type{ PositionModeResponse }, name::Symbol, val)
end
