# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""account_200_response_assets_inner

    Account200ResponseAssetsInner(;
        asset=nothing,
        walletBalance=nothing,
        unrealizedProfit=nothing,
        marginBalance=nothing,
        maintMargin=nothing,
        initialMargin=nothing,
        positionInitialMargin=nothing,
        openOrderInitialMargin=nothing,
        crossWalletBalance=nothing,
        crossUnPnl=nothing,
        availableBalance=nothing,
        maxWithdrawAmount=nothing,
    )

    - asset::String : Asset name
    - walletBalance::String : Wallet balance
    - unrealizedProfit::String : Unrealized profit
    - marginBalance::String : Margin balance
    - maintMargin::String : Maintenance margin
    - initialMargin::String : Initial margin
    - positionInitialMargin::String : Position initial margin
    - openOrderInitialMargin::String : Open order initial margin
    - crossWalletBalance::String : Cross wallet balance
    - crossUnPnl::String : Cross unrealized PnL
    - availableBalance::String : Available balance
    - maxWithdrawAmount::String : Maximum withdraw amount
"""
Base.@kwdef mutable struct Account200ResponseAssetsInner <: OpenAPI.APIModel
    asset::Union{Nothing, String} = nothing
    walletBalance::Union{Nothing, String} = nothing
    unrealizedProfit::Union{Nothing, String} = nothing
    marginBalance::Union{Nothing, String} = nothing
    maintMargin::Union{Nothing, String} = nothing
    initialMargin::Union{Nothing, String} = nothing
    positionInitialMargin::Union{Nothing, String} = nothing
    openOrderInitialMargin::Union{Nothing, String} = nothing
    crossWalletBalance::Union{Nothing, String} = nothing
    crossUnPnl::Union{Nothing, String} = nothing
    availableBalance::Union{Nothing, String} = nothing
    maxWithdrawAmount::Union{Nothing, String} = nothing

    function Account200ResponseAssetsInner(asset, walletBalance, unrealizedProfit, marginBalance, maintMargin, initialMargin, positionInitialMargin, openOrderInitialMargin, crossWalletBalance, crossUnPnl, availableBalance, maxWithdrawAmount, )
        OpenAPI.validate_property(Account200ResponseAssetsInner, Symbol("asset"), asset)
        OpenAPI.validate_property(Account200ResponseAssetsInner, Symbol("walletBalance"), walletBalance)
        OpenAPI.validate_property(Account200ResponseAssetsInner, Symbol("unrealizedProfit"), unrealizedProfit)
        OpenAPI.validate_property(Account200ResponseAssetsInner, Symbol("marginBalance"), marginBalance)
        OpenAPI.validate_property(Account200ResponseAssetsInner, Symbol("maintMargin"), maintMargin)
        OpenAPI.validate_property(Account200ResponseAssetsInner, Symbol("initialMargin"), initialMargin)
        OpenAPI.validate_property(Account200ResponseAssetsInner, Symbol("positionInitialMargin"), positionInitialMargin)
        OpenAPI.validate_property(Account200ResponseAssetsInner, Symbol("openOrderInitialMargin"), openOrderInitialMargin)
        OpenAPI.validate_property(Account200ResponseAssetsInner, Symbol("crossWalletBalance"), crossWalletBalance)
        OpenAPI.validate_property(Account200ResponseAssetsInner, Symbol("crossUnPnl"), crossUnPnl)
        OpenAPI.validate_property(Account200ResponseAssetsInner, Symbol("availableBalance"), availableBalance)
        OpenAPI.validate_property(Account200ResponseAssetsInner, Symbol("maxWithdrawAmount"), maxWithdrawAmount)
        return new(asset, walletBalance, unrealizedProfit, marginBalance, maintMargin, initialMargin, positionInitialMargin, openOrderInitialMargin, crossWalletBalance, crossUnPnl, availableBalance, maxWithdrawAmount, )
    end
end # type Account200ResponseAssetsInner

const _property_types_Account200ResponseAssetsInner = Dict{Symbol,String}(Symbol("asset")=>"String", Symbol("walletBalance")=>"String", Symbol("unrealizedProfit")=>"String", Symbol("marginBalance")=>"String", Symbol("maintMargin")=>"String", Symbol("initialMargin")=>"String", Symbol("positionInitialMargin")=>"String", Symbol("openOrderInitialMargin")=>"String", Symbol("crossWalletBalance")=>"String", Symbol("crossUnPnl")=>"String", Symbol("availableBalance")=>"String", Symbol("maxWithdrawAmount")=>"String", )
OpenAPI.property_type(::Type{ Account200ResponseAssetsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Account200ResponseAssetsInner[name]))}

function check_required(o::Account200ResponseAssetsInner)
    true
end

function OpenAPI.validate_property(::Type{ Account200ResponseAssetsInner }, name::Symbol, val)












end
