# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ApiTradingStatusResponse_triggerCondition

    ApiTradingStatusResponseTriggerCondition(;
        GCR=nothing,
        IFER=nothing,
        UFR=nothing,
    )

    - GCR::Int64 : Number of GTC orders
    - IFER::Int64 : Number of FOK/IOC orders
    - UFR::Int64 : Number of orders
"""
Base.@kwdef mutable struct ApiTradingStatusResponseTriggerCondition <: OpenAPI.APIModel
    GCR::Union{Nothing, Int64} = nothing
    IFER::Union{Nothing, Int64} = nothing
    UFR::Union{Nothing, Int64} = nothing

    function ApiTradingStatusResponseTriggerCondition(GCR, IFER, UFR, )
        OpenAPI.validate_property(ApiTradingStatusResponseTriggerCondition, Symbol("GCR"), GCR)
        OpenAPI.validate_property(ApiTradingStatusResponseTriggerCondition, Symbol("IFER"), IFER)
        OpenAPI.validate_property(ApiTradingStatusResponseTriggerCondition, Symbol("UFR"), UFR)
        return new(GCR, IFER, UFR, )
    end
end # type ApiTradingStatusResponseTriggerCondition

const _property_types_ApiTradingStatusResponseTriggerCondition = Dict{Symbol,String}(Symbol("GCR")=>"Int64", Symbol("IFER")=>"Int64", Symbol("UFR")=>"Int64", )
OpenAPI.property_type(::Type{ ApiTradingStatusResponseTriggerCondition }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ApiTradingStatusResponseTriggerCondition[name]))}

function check_required(o::ApiTradingStatusResponseTriggerCondition)
    true
end

function OpenAPI.validate_property(::Type{ ApiTradingStatusResponseTriggerCondition }, name::Symbol, val)
end
