# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BookTickerResponseO

    BookTickerResponseO(;
        symbol=nothing,
        bidPrice=nothing,
        bidQty=nothing,
        askPrice=nothing,
        askQty=nothing,
        time=nothing,
    )

    - symbol::String : Trading pair symbol
    - bidPrice::String : Best bid price
    - bidQty::String : Best bid quantity
    - askPrice::String : Best ask price
    - askQty::String : Best ask quantity
    - time::Int64 : Update time
"""
Base.@kwdef mutable struct BookTickerResponseO <: OpenAPI.APIModel
    symbol::Union{Nothing, String} = nothing
    bidPrice::Union{Nothing, String} = nothing
    bidQty::Union{Nothing, String} = nothing
    askPrice::Union{Nothing, String} = nothing
    askQty::Union{Nothing, String} = nothing
    time::Union{Nothing, Int64} = nothing

    function BookTickerResponseO(symbol, bidPrice, bidQty, askPrice, askQty, time, )
        OpenAPI.validate_property(BookTickerResponseO, Symbol("symbol"), symbol)
        OpenAPI.validate_property(BookTickerResponseO, Symbol("bidPrice"), bidPrice)
        OpenAPI.validate_property(BookTickerResponseO, Symbol("bidQty"), bidQty)
        OpenAPI.validate_property(BookTickerResponseO, Symbol("askPrice"), askPrice)
        OpenAPI.validate_property(BookTickerResponseO, Symbol("askQty"), askQty)
        OpenAPI.validate_property(BookTickerResponseO, Symbol("time"), time)
        return new(symbol, bidPrice, bidQty, askPrice, askQty, time, )
    end
end # type BookTickerResponseO

const _property_types_BookTickerResponseO = Dict{Symbol,String}(Symbol("symbol")=>"String", Symbol("bidPrice")=>"String", Symbol("bidQty")=>"String", Symbol("askPrice")=>"String", Symbol("askQty")=>"String", Symbol("time")=>"Int64", )
OpenAPI.property_type(::Type{ BookTickerResponseO }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BookTickerResponseO[name]))}

function check_required(o::BookTickerResponseO)
    true
end

function OpenAPI.validate_property(::Type{ BookTickerResponseO }, name::Symbol, val)






    if name === Symbol("time")
        OpenAPI.validate_param(name, "BookTickerResponseO", :format, val, "int64")
    end
end
