# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""OrderResponse

    OrderResponse(;
        clientOrderId=nothing,
        cumQty=nothing,
        cumQuote=nothing,
        executedQty=nothing,
        orderId=nothing,
        avgPrice=nothing,
        origQty=nothing,
        price=nothing,
        reduceOnly=nothing,
        side=nothing,
        positionSide=nothing,
        status=nothing,
        stopPrice=nothing,
        closePosition=nothing,
        symbol=nothing,
        timeInForce=nothing,
        type=nothing,
        origType=nothing,
        activatePrice=nothing,
        priceRate=nothing,
        updateTime=nothing,
        workingType=nothing,
        priceProtect=nothing,
    )

    - clientOrderId::String : Client order ID
    - cumQty::String : Cumulative filled quantity
    - cumQuote::String : Cumulative quote asset filled quantity
    - executedQty::String : Executed quantity
    - orderId::Int64 : Order ID
    - avgPrice::String : Average fill price
    - origQty::String : Original quantity
    - price::String : Order price
    - reduceOnly::Bool : Reduce only flag
    - side::String : Order side (BUY/SELL)
    - positionSide::String : Position side (BOTH/LONG/SHORT)
    - status::String : Order status
    - stopPrice::String : Stop price
    - closePosition::Bool : Close position flag
    - symbol::String : Trading pair symbol
    - timeInForce::String : Time in force
    - type::String : Order type
    - origType::String : Original order type
    - activatePrice::String : Activation price for trailing stop orders
    - priceRate::String : Callback rate for trailing stop orders
    - updateTime::Int64 : Last update timestamp
    - workingType::String : Working type (MARK_PRICE/CONTRACT_PRICE)
    - priceProtect::Bool : Price protection flag
"""
Base.@kwdef mutable struct OrderResponse <: OpenAPI.APIModel
    clientOrderId::Union{Nothing, String} = nothing
    cumQty::Union{Nothing, String} = nothing
    cumQuote::Union{Nothing, String} = nothing
    executedQty::Union{Nothing, String} = nothing
    orderId::Union{Nothing, Int64} = nothing
    avgPrice::Union{Nothing, String} = nothing
    origQty::Union{Nothing, String} = nothing
    price::Union{Nothing, String} = nothing
    reduceOnly::Union{Nothing, Bool} = nothing
    side::Union{Nothing, String} = nothing
    positionSide::Union{Nothing, String} = nothing
    status::Union{Nothing, String} = nothing
    stopPrice::Union{Nothing, String} = nothing
    closePosition::Union{Nothing, Bool} = nothing
    symbol::Union{Nothing, String} = nothing
    timeInForce::Union{Nothing, String} = nothing
    type::Union{Nothing, String} = nothing
    origType::Union{Nothing, String} = nothing
    activatePrice::Union{Nothing, String} = nothing
    priceRate::Union{Nothing, String} = nothing
    updateTime::Union{Nothing, Int64} = nothing
    workingType::Union{Nothing, String} = nothing
    priceProtect::Union{Nothing, Bool} = nothing

    function OrderResponse(clientOrderId, cumQty, cumQuote, executedQty, orderId, avgPrice, origQty, price, reduceOnly, side, positionSide, status, stopPrice, closePosition, symbol, timeInForce, type, origType, activatePrice, priceRate, updateTime, workingType, priceProtect, )
        OpenAPI.validate_property(OrderResponse, Symbol("clientOrderId"), clientOrderId)
        OpenAPI.validate_property(OrderResponse, Symbol("cumQty"), cumQty)
        OpenAPI.validate_property(OrderResponse, Symbol("cumQuote"), cumQuote)
        OpenAPI.validate_property(OrderResponse, Symbol("executedQty"), executedQty)
        OpenAPI.validate_property(OrderResponse, Symbol("orderId"), orderId)
        OpenAPI.validate_property(OrderResponse, Symbol("avgPrice"), avgPrice)
        OpenAPI.validate_property(OrderResponse, Symbol("origQty"), origQty)
        OpenAPI.validate_property(OrderResponse, Symbol("price"), price)
        OpenAPI.validate_property(OrderResponse, Symbol("reduceOnly"), reduceOnly)
        OpenAPI.validate_property(OrderResponse, Symbol("side"), side)
        OpenAPI.validate_property(OrderResponse, Symbol("positionSide"), positionSide)
        OpenAPI.validate_property(OrderResponse, Symbol("status"), status)
        OpenAPI.validate_property(OrderResponse, Symbol("stopPrice"), stopPrice)
        OpenAPI.validate_property(OrderResponse, Symbol("closePosition"), closePosition)
        OpenAPI.validate_property(OrderResponse, Symbol("symbol"), symbol)
        OpenAPI.validate_property(OrderResponse, Symbol("timeInForce"), timeInForce)
        OpenAPI.validate_property(OrderResponse, Symbol("type"), type)
        OpenAPI.validate_property(OrderResponse, Symbol("origType"), origType)
        OpenAPI.validate_property(OrderResponse, Symbol("activatePrice"), activatePrice)
        OpenAPI.validate_property(OrderResponse, Symbol("priceRate"), priceRate)
        OpenAPI.validate_property(OrderResponse, Symbol("updateTime"), updateTime)
        OpenAPI.validate_property(OrderResponse, Symbol("workingType"), workingType)
        OpenAPI.validate_property(OrderResponse, Symbol("priceProtect"), priceProtect)
        return new(clientOrderId, cumQty, cumQuote, executedQty, orderId, avgPrice, origQty, price, reduceOnly, side, positionSide, status, stopPrice, closePosition, symbol, timeInForce, type, origType, activatePrice, priceRate, updateTime, workingType, priceProtect, )
    end
end # type OrderResponse

const _property_types_OrderResponse = Dict{Symbol,String}(Symbol("clientOrderId")=>"String", Symbol("cumQty")=>"String", Symbol("cumQuote")=>"String", Symbol("executedQty")=>"String", Symbol("orderId")=>"Int64", Symbol("avgPrice")=>"String", Symbol("origQty")=>"String", Symbol("price")=>"String", Symbol("reduceOnly")=>"Bool", Symbol("side")=>"String", Symbol("positionSide")=>"String", Symbol("status")=>"String", Symbol("stopPrice")=>"String", Symbol("closePosition")=>"Bool", Symbol("symbol")=>"String", Symbol("timeInForce")=>"String", Symbol("type")=>"String", Symbol("origType")=>"String", Symbol("activatePrice")=>"String", Symbol("priceRate")=>"String", Symbol("updateTime")=>"Int64", Symbol("workingType")=>"String", Symbol("priceProtect")=>"Bool", )
OpenAPI.property_type(::Type{ OrderResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrderResponse[name]))}

function check_required(o::OrderResponse)
    true
end

function OpenAPI.validate_property(::Type{ OrderResponse }, name::Symbol, val)





    if name === Symbol("orderId")
        OpenAPI.validate_param(name, "OrderResponse", :format, val, "int64")
    end





    if name === Symbol("side")
        OpenAPI.validate_param(name, "OrderResponse", :enum, val, ["BUY", "SELL"])
    end


    if name === Symbol("positionSide")
        OpenAPI.validate_param(name, "OrderResponse", :enum, val, ["BOTH", "LONG", "SHORT"])
    end


    if name === Symbol("status")
        OpenAPI.validate_param(name, "OrderResponse", :enum, val, ["NEW", "PARTIALLY_FILLED", "FILLED", "CANCELED", "REJECTED", "EXPIRED"])
    end





    if name === Symbol("timeInForce")
        OpenAPI.validate_param(name, "OrderResponse", :enum, val, ["GTC", "IOC", "FOK", "GTX"])
    end


    if name === Symbol("type")
        OpenAPI.validate_param(name, "OrderResponse", :enum, val, ["LIMIT", "MARKET", "STOP", "STOP_MARKET", "TAKE_PROFIT", "TAKE_PROFIT_MARKET", "TRAILING_STOP_MARKET"])
    end


    if name === Symbol("origType")
        OpenAPI.validate_param(name, "OrderResponse", :enum, val, ["LIMIT", "MARKET", "STOP", "STOP_MARKET", "TAKE_PROFIT", "TAKE_PROFIT_MARKET", "TRAILING_STOP_MARKET"])
    end




    if name === Symbol("updateTime")
        OpenAPI.validate_param(name, "OrderResponse", :format, val, "int64")
    end

    if name === Symbol("workingType")
        OpenAPI.validate_param(name, "OrderResponse", :enum, val, ["MARK_PRICE", "CONTRACT_PRICE"])
    end


end
