# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ListenKeyResponse

    ListenKeyResponse(;
        listenKey=nothing,
    )

    - listenKey::String : User data stream listen key
"""
Base.@kwdef mutable struct ListenKeyResponse <: OpenAPI.APIModel
    listenKey::Union{Nothing, String} = nothing

    function ListenKeyResponse(listenKey, )
        OpenAPI.validate_property(ListenKeyResponse, Symbol("listenKey"), listenKey)
        return new(listenKey, )
    end
end # type ListenKeyResponse

const _property_types_ListenKeyResponse = Dict{Symbol,String}(Symbol("listenKey")=>"String", )
OpenAPI.property_type(::Type{ ListenKeyResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListenKeyResponse[name]))}

function check_required(o::ListenKeyResponse)
    true
end

function OpenAPI.validate_property(::Type{ ListenKeyResponse }, name::Symbol, val)
end
