# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""KlinesResponse_inner_inner

    KlinesResponseInnerInner(; value=nothing)
"""
mutable struct KlinesResponseInnerInner <: OpenAPI.OneOfAPIModel
    value::Any # Union{ Int64, String }
    KlinesResponseInnerInner() = new()
    KlinesResponseInnerInner(value) = new(value)
end # type KlinesResponseInnerInner

function OpenAPI.property_type(::Type{ KlinesResponseInnerInner }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(KlinesResponseInnerInner, name)
end
