# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""serverTime_200_response

    ServerTime200Response(;
        serverTime=nothing,
    )

    - serverTime::Int64 : Current server time in milliseconds
"""
Base.@kwdef mutable struct ServerTime200Response <: OpenAPI.APIModel
    serverTime::Union{Nothing, Int64} = nothing

    function ServerTime200Response(serverTime, )
        OpenAPI.validate_property(ServerTime200Response, Symbol("serverTime"), serverTime)
        return new(serverTime, )
    end
end # type ServerTime200Response

const _property_types_ServerTime200Response = Dict{Symbol,String}(Symbol("serverTime")=>"Int64", )
OpenAPI.property_type(::Type{ ServerTime200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ServerTime200Response[name]))}

function check_required(o::ServerTime200Response)
    o.serverTime === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ServerTime200Response }, name::Symbol, val)
    if name === Symbol("serverTime")
        OpenAPI.validate_param(name, "ServerTime200Response", :format, val, "int64")
    end
end
