# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PortfolioMarginAccountResponse

    PortfolioMarginAccountResponse(;
        totalCollateral=nothing,
        totalMarginBalance=nothing,
        totalInitialMargin=nothing,
        totalMaintenanceMargin=nothing,
        totalPositionInitialMargin=nothing,
        totalOpenOrderInitialMargin=nothing,
        totalUnrealizedProfit=nothing,
        totalLiabilities=nothing,
        availableBalance=nothing,
        assets=nothing,
        positions=nothing,
    )

    - totalCollateral::String : Total collateral value in USD
    - totalMarginBalance::String : Total margin balance in USD
    - totalInitialMargin::String : Total initial margin required in USD
    - totalMaintenanceMargin::String : Total maintenance margin required in USD
    - totalPositionInitialMargin::String : Total position initial margin in USD
    - totalOpenOrderInitialMargin::String : Total open order initial margin in USD
    - totalUnrealizedProfit::String : Total unrealized profit in USD
    - totalLiabilities::String : Total liabilities in USD
    - availableBalance::String : Available balance in USD
    - assets::Vector{PortfolioMarginAccountResponseAssetsInner} : List of asset details
    - positions::Vector{PortfolioMarginAccountResponsePositionsInner} : List of positions
"""
Base.@kwdef mutable struct PortfolioMarginAccountResponse <: OpenAPI.APIModel
    totalCollateral::Union{Nothing, String} = nothing
    totalMarginBalance::Union{Nothing, String} = nothing
    totalInitialMargin::Union{Nothing, String} = nothing
    totalMaintenanceMargin::Union{Nothing, String} = nothing
    totalPositionInitialMargin::Union{Nothing, String} = nothing
    totalOpenOrderInitialMargin::Union{Nothing, String} = nothing
    totalUnrealizedProfit::Union{Nothing, String} = nothing
    totalLiabilities::Union{Nothing, String} = nothing
    availableBalance::Union{Nothing, String} = nothing
    assets::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PortfolioMarginAccountResponseAssetsInner} }
    positions::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PortfolioMarginAccountResponsePositionsInner} }

    function PortfolioMarginAccountResponse(totalCollateral, totalMarginBalance, totalInitialMargin, totalMaintenanceMargin, totalPositionInitialMargin, totalOpenOrderInitialMargin, totalUnrealizedProfit, totalLiabilities, availableBalance, assets, positions, )
        OpenAPI.validate_property(PortfolioMarginAccountResponse, Symbol("totalCollateral"), totalCollateral)
        OpenAPI.validate_property(PortfolioMarginAccountResponse, Symbol("totalMarginBalance"), totalMarginBalance)
        OpenAPI.validate_property(PortfolioMarginAccountResponse, Symbol("totalInitialMargin"), totalInitialMargin)
        OpenAPI.validate_property(PortfolioMarginAccountResponse, Symbol("totalMaintenanceMargin"), totalMaintenanceMargin)
        OpenAPI.validate_property(PortfolioMarginAccountResponse, Symbol("totalPositionInitialMargin"), totalPositionInitialMargin)
        OpenAPI.validate_property(PortfolioMarginAccountResponse, Symbol("totalOpenOrderInitialMargin"), totalOpenOrderInitialMargin)
        OpenAPI.validate_property(PortfolioMarginAccountResponse, Symbol("totalUnrealizedProfit"), totalUnrealizedProfit)
        OpenAPI.validate_property(PortfolioMarginAccountResponse, Symbol("totalLiabilities"), totalLiabilities)
        OpenAPI.validate_property(PortfolioMarginAccountResponse, Symbol("availableBalance"), availableBalance)
        OpenAPI.validate_property(PortfolioMarginAccountResponse, Symbol("assets"), assets)
        OpenAPI.validate_property(PortfolioMarginAccountResponse, Symbol("positions"), positions)
        return new(totalCollateral, totalMarginBalance, totalInitialMargin, totalMaintenanceMargin, totalPositionInitialMargin, totalOpenOrderInitialMargin, totalUnrealizedProfit, totalLiabilities, availableBalance, assets, positions, )
    end
end # type PortfolioMarginAccountResponse

const _property_types_PortfolioMarginAccountResponse = Dict{Symbol,String}(Symbol("totalCollateral")=>"String", Symbol("totalMarginBalance")=>"String", Symbol("totalInitialMargin")=>"String", Symbol("totalMaintenanceMargin")=>"String", Symbol("totalPositionInitialMargin")=>"String", Symbol("totalOpenOrderInitialMargin")=>"String", Symbol("totalUnrealizedProfit")=>"String", Symbol("totalLiabilities")=>"String", Symbol("availableBalance")=>"String", Symbol("assets")=>"Vector{PortfolioMarginAccountResponseAssetsInner}", Symbol("positions")=>"Vector{PortfolioMarginAccountResponsePositionsInner}", )
OpenAPI.property_type(::Type{ PortfolioMarginAccountResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PortfolioMarginAccountResponse[name]))}

function check_required(o::PortfolioMarginAccountResponse)
    true
end

function OpenAPI.validate_property(::Type{ PortfolioMarginAccountResponse }, name::Symbol, val)











end
