# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""userTrades_200_response_inner

    UserTrades200ResponseInner(;
        buyer=nothing,
        commission=nothing,
        commissionAsset=nothing,
        id=nothing,
        maker=nothing,
        orderId=nothing,
        price=nothing,
        qty=nothing,
        quoteQty=nothing,
        realizedPnl=nothing,
        side=nothing,
        positionSide=nothing,
        symbol=nothing,
        time=nothing,
    )

    - buyer::Bool : true if the buyer is the taker
    - commission::String : Commission
    - commissionAsset::String : Commission asset
    - id::Int64 : Trade ID
    - maker::Bool : true if the trade was a maker trade
    - orderId::Int64 : Order ID
    - price::String : Price
    - qty::String : Quantity
    - quoteQty::String : Quote quantity
    - realizedPnl::String : Realized profit and loss
    - side::String : Side of the trade (BUY or SELL)
    - positionSide::String : Position side (LONG, SHORT, or BOTH)
    - symbol::String : Symbol
    - time::Int64 : Trade time
"""
Base.@kwdef mutable struct UserTrades200ResponseInner <: OpenAPI.APIModel
    buyer::Union{Nothing, Bool} = nothing
    commission::Union{Nothing, String} = nothing
    commissionAsset::Union{Nothing, String} = nothing
    id::Union{Nothing, Int64} = nothing
    maker::Union{Nothing, Bool} = nothing
    orderId::Union{Nothing, Int64} = nothing
    price::Union{Nothing, String} = nothing
    qty::Union{Nothing, String} = nothing
    quoteQty::Union{Nothing, String} = nothing
    realizedPnl::Union{Nothing, String} = nothing
    side::Union{Nothing, String} = nothing
    positionSide::Union{Nothing, String} = nothing
    symbol::Union{Nothing, String} = nothing
    time::Union{Nothing, Int64} = nothing

    function UserTrades200ResponseInner(buyer, commission, commissionAsset, id, maker, orderId, price, qty, quoteQty, realizedPnl, side, positionSide, symbol, time, )
        OpenAPI.validate_property(UserTrades200ResponseInner, Symbol("buyer"), buyer)
        OpenAPI.validate_property(UserTrades200ResponseInner, Symbol("commission"), commission)
        OpenAPI.validate_property(UserTrades200ResponseInner, Symbol("commissionAsset"), commissionAsset)
        OpenAPI.validate_property(UserTrades200ResponseInner, Symbol("id"), id)
        OpenAPI.validate_property(UserTrades200ResponseInner, Symbol("maker"), maker)
        OpenAPI.validate_property(UserTrades200ResponseInner, Symbol("orderId"), orderId)
        OpenAPI.validate_property(UserTrades200ResponseInner, Symbol("price"), price)
        OpenAPI.validate_property(UserTrades200ResponseInner, Symbol("qty"), qty)
        OpenAPI.validate_property(UserTrades200ResponseInner, Symbol("quoteQty"), quoteQty)
        OpenAPI.validate_property(UserTrades200ResponseInner, Symbol("realizedPnl"), realizedPnl)
        OpenAPI.validate_property(UserTrades200ResponseInner, Symbol("side"), side)
        OpenAPI.validate_property(UserTrades200ResponseInner, Symbol("positionSide"), positionSide)
        OpenAPI.validate_property(UserTrades200ResponseInner, Symbol("symbol"), symbol)
        OpenAPI.validate_property(UserTrades200ResponseInner, Symbol("time"), time)
        return new(buyer, commission, commissionAsset, id, maker, orderId, price, qty, quoteQty, realizedPnl, side, positionSide, symbol, time, )
    end
end # type UserTrades200ResponseInner

const _property_types_UserTrades200ResponseInner = Dict{Symbol,String}(Symbol("buyer")=>"Bool", Symbol("commission")=>"String", Symbol("commissionAsset")=>"String", Symbol("id")=>"Int64", Symbol("maker")=>"Bool", Symbol("orderId")=>"Int64", Symbol("price")=>"String", Symbol("qty")=>"String", Symbol("quoteQty")=>"String", Symbol("realizedPnl")=>"String", Symbol("side")=>"String", Symbol("positionSide")=>"String", Symbol("symbol")=>"String", Symbol("time")=>"Int64", )
OpenAPI.property_type(::Type{ UserTrades200ResponseInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UserTrades200ResponseInner[name]))}

function check_required(o::UserTrades200ResponseInner)
    true
end

function OpenAPI.validate_property(::Type{ UserTrades200ResponseInner }, name::Symbol, val)
end
