# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""bookTicker_200_response

    BookTicker200Response(; value=nothing)
"""
mutable struct BookTicker200Response <: OpenAPI.OneOfAPIModel
    value::Any # Union{ BookTickerResponseO, Vector{BookTickerResponseO} }
    BookTicker200Response() = new()
    BookTicker200Response(value) = new(value)
end # type BookTicker200Response

function OpenAPI.property_type(::Type{ BookTicker200Response }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(BookTicker200Response, name)
end
