# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ApiTradingStatusResponse_indicators

    ApiTradingStatusResponseIndicators(;
        BTCUSDT=nothing,
    )

    - BTCUSDT::ApiTradingStatusResponseIndicatorsBTCUSDT
"""
Base.@kwdef mutable struct ApiTradingStatusResponseIndicators <: OpenAPI.APIModel
    BTCUSDT = nothing # spec type: Union{ Nothing, ApiTradingStatusResponseIndicatorsBTCUSDT }

    function ApiTradingStatusResponseIndicators(BTCUSDT, )
        OpenAPI.validate_property(ApiTradingStatusResponseIndicators, Symbol("BTCUSDT"), BTCUSDT)
        return new(BTCUSDT, )
    end
end # type ApiTradingStatusResponseIndicators

const _property_types_ApiTradingStatusResponseIndicators = Dict{Symbol,String}(Symbol("BTCUSDT")=>"ApiTradingStatusResponseIndicatorsBTCUSDT", )
OpenAPI.property_type(::Type{ ApiTradingStatusResponseIndicators }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ApiTradingStatusResponseIndicators[name]))}

function check_required(o::ApiTradingStatusResponseIndicators)
    true
end

function OpenAPI.validate_property(::Type{ ApiTradingStatusResponseIndicators }, name::Symbol, val)

end
