# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct PortfolioMarginApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `PortfolioMarginApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ PortfolioMarginApi }) = "https://fapi.binance.com"

const _returntypes_get_p_m_account_info_PortfolioMarginApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => PortfolioMarginAccountResponse,
)

function _oacinternal_get_p_m_account_info(_api::PortfolioMarginApi; asset=nothing, recv_window=nothing, timestamp=nothing, signature=nothing, x_mbx_apikey=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_p_m_account_info_PortfolioMarginApi, "/fapi/v1/pmAccountInfo", [])
    OpenAPI.Clients.set_param(_ctx.query, "asset", asset; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "recvWindow", recv_window; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "timestamp", timestamp; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "signature", signature; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.header, "x-mbx-apikey", x_mbx_apikey)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Portfolio Margin Account Information

Portfolio Margin Account Information

Params:
- asset::String
- recv_window::String
- timestamp::String
- signature::String
- x_mbx_apikey::String

Return: PortfolioMarginAccountResponse, OpenAPI.Clients.ApiResponse
"""
function get_p_m_account_info(_api::PortfolioMarginApi; asset=nothing, recv_window=nothing, timestamp=nothing, signature=nothing, x_mbx_apikey=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_p_m_account_info(_api; asset=asset, recv_window=recv_window, timestamp=timestamp, signature=signature, x_mbx_apikey=x_mbx_apikey, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_p_m_account_info(_api::PortfolioMarginApi, response_stream::Channel; asset=nothing, recv_window=nothing, timestamp=nothing, signature=nothing, x_mbx_apikey=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_p_m_account_info(_api; asset=asset, recv_window=recv_window, timestamp=timestamp, signature=signature, x_mbx_apikey=x_mbx_apikey, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export get_p_m_account_info
