# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

module APIClient

using Dates, TimeZones
using OpenAPI
using OpenAPI.Clients

const API_VERSION = "1.0.0"

include("modelincludes.jl")

include("apis/api_AccountApi.jl")
include("apis/api_DataStreamApi.jl")
include("apis/api_MarketApi.jl")
include("apis/api_OrderApi.jl")
include("apis/api_PortfolioMarginApi.jl")
include("apis/api_TradeApi.jl")

end # module APIClient
