# Has been generated by AI from code found in the APIs generated by the OpenAPI Code Generator

const PARAM_CASE_MAPPING = Dict{Symbol,String}(
    # Order Parameters
    :time_in_force => "timeInForce",
    :recv_window => "recvWindow",
    :order_id => "orderId",
    :orig_client_order_id => "origClientOrderId", 
    :new_client_order_id => "newClientOrderId",
    :position_side => "positionSide",
    :stop_price => "stopPrice",
    :close_position => "closePosition",
    :activation_price => "activationPrice",
    :callback_rate => "callbackRate",
    :working_type => "workingType",
    :price_protect => "priceProtect",
    :reduce_only => "reduceOnly",
    :price_match => "priceMatch",
    :self_trade_prevention_mode => "selfTradePreventionMode",
    :good_till_date => "goodTillDate",
    :new_order_resp_type => "newOrderRespType",
    :batch_orders => "batchOrders",

    # Account Parameters
    :margin_type => "marginType",
    :multi_assets_margin => "multiAssetsMargin",
    :dual_side_position => "dualSidePosition",

    # Market Data Parameters
    :start_time => "startTime",
    :end_time => "endTime",
    :from_id => "fromId",
    :income_type => "incomeType",
    :download_id => "downloadId",

    # Common Parameters
    :x_mbx_apikey => "x-mbx-apikey"
)